# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

env:
matrix:
  include:
    - os: linux
      env:
    - os: linux
      dist: xenial
      env:
      addons:
        apt:
          packages:
            - g++-4.9
      before_install:
        - mkdir -p ~/.R
        - echo "CXX11=g++-4.9"  > ~/.R/Makevars
        - echo "CXX=g++-4.9" >> ~/.R/Makevars
        - cat ~/.R/Makevars
    - os: osx
      env:
  allow_failures:
    - os: linux
      env: TORCH_BINARIES=https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip

sudo: true
cache: packages
warnings_are_errors: false

after_success:
    - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
