# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
 - wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-latest.zip
 - unzip libtorch-shared-with-deps-latest.zip -d /usr/local/lib/
