# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_grad_mode <- function(enabled) {
    invisible(.Call('_torch_set_grad_mode', PACKAGE = 'torch', enabled))
}

tensor_from_r_ <- function(x, dim, dtype, device, requires_grad = FALSE) {
    .Call('_torch_tensor_from_r_', PACKAGE = 'torch', x, dim, dtype, device, requires_grad)
}

tensor_ <- function(x, dtype, device, requires_grad) {
    .Call('_torch_tensor_', PACKAGE = 'torch', x, dtype, device, requires_grad)
}

as_array_tensor_ <- function(x) {
    .Call('_torch_as_array_tensor_', PACKAGE = 'torch', x)
}

torch_randn_ <- function(size) {
    .Call('_torch_torch_randn_', PACKAGE = 'torch', size)
}

tensor_print_ <- function(x) {
    invisible(.Call('_torch_tensor_print_', PACKAGE = 'torch', x))
}

tensor_abs_ <- function(x) {
    .Call('_torch_tensor_abs_', PACKAGE = 'torch', x)
}

tensor_acos_ <- function(x) {
    .Call('_torch_tensor_acos_', PACKAGE = 'torch', x)
}

tensor_add_tensor_ <- function(x, y) {
    .Call('_torch_tensor_add_tensor_', PACKAGE = 'torch', x, y)
}

tensor_add_scalar_ <- function(x, y) {
    .Call('_torch_tensor_add_scalar_', PACKAGE = 'torch', x, y)
}

tensor_addbmm_ <- function(x, batch1, batch2, beta, alpha) {
    .Call('_torch_tensor_addbmm_', PACKAGE = 'torch', x, batch1, batch2, beta, alpha)
}

tensor_addcdiv_ <- function(x, tensor1, tensor2, value) {
    .Call('_torch_tensor_addcdiv_', PACKAGE = 'torch', x, tensor1, tensor2, value)
}

tensor_addcmul_ <- function(x, tensor1, tensor2, value) {
    .Call('_torch_tensor_addcmul_', PACKAGE = 'torch', x, tensor1, tensor2, value)
}

tensor_addmm_ <- function(x, mat1, mat2, beta, alpha) {
    .Call('_torch_tensor_addmm_', PACKAGE = 'torch', x, mat1, mat2, beta, alpha)
}

tensor_addmv_ <- function(x, mat, vec, beta, alpha) {
    .Call('_torch_tensor_addmv_', PACKAGE = 'torch', x, mat, vec, beta, alpha)
}

tensor_addr_ <- function(x, vec1, vec2, beta, alpha) {
    .Call('_torch_tensor_addr_', PACKAGE = 'torch', x, vec1, vec2, beta, alpha)
}

tensor_all_ <- function(x, dim, keepdim) {
    .Call('_torch_tensor_all_', PACKAGE = 'torch', x, dim, keepdim)
}

tensor_allclose_ <- function(x, other, rtol, atol, equal_nan) {
    .Call('_torch_tensor_allclose_', PACKAGE = 'torch', x, other, rtol, atol, equal_nan)
}

tensor_any_ <- function(x, dim, keepdim) {
    .Call('_torch_tensor_any_', PACKAGE = 'torch', x, dim, keepdim)
}

tensor_argmax_ <- function(x, dim, keepdim) {
    .Call('_torch_tensor_argmax_', PACKAGE = 'torch', x, dim, keepdim)
}

tensor_argmin_ <- function(x, dim, keepdim) {
    .Call('_torch_tensor_argmin_', PACKAGE = 'torch', x, dim, keepdim)
}

tensor_as_strided_ <- function(x, size, stride, storage_offset) {
    .Call('_torch_tensor_as_strided_', PACKAGE = 'torch', x, size, stride, storage_offset)
}

tensor_to_string_ <- function(x) {
    .Call('_torch_tensor_to_string_', PACKAGE = 'torch', x)
}

tensor_asin_ <- function(x) {
    .Call('_torch_tensor_asin_', PACKAGE = 'torch', x)
}

tensor_atan_ <- function(x) {
    .Call('_torch_tensor_atan_', PACKAGE = 'torch', x)
}

tensor_atan2_ <- function(x, other) {
    .Call('_torch_tensor_atan2_', PACKAGE = 'torch', x, other)
}

tensor_backward_ <- function(x, gradient, keep_graph, create_graph) {
    invisible(.Call('_torch_tensor_backward_', PACKAGE = 'torch', x, gradient, keep_graph, create_graph))
}

tensor_baddbmm_ <- function(x, batch1, batch2, beta, alpha) {
    .Call('_torch_tensor_baddbmm_', PACKAGE = 'torch', x, batch1, batch2, beta, alpha)
}

tensor_bernoulli_ <- function(x, p) {
    .Call('_torch_tensor_bernoulli_', PACKAGE = 'torch', x, p)
}

tensor_bincount_ <- function(x, weights, minlength) {
    .Call('_torch_tensor_bincount_', PACKAGE = 'torch', x, weights, minlength)
}

tensor_bmm_ <- function(x, mat2) {
    .Call('_torch_tensor_bmm_', PACKAGE = 'torch', x, mat2)
}

tensor_btrifact_ <- function(x, pivot) {
    .Call('_torch_tensor_btrifact_', PACKAGE = 'torch', x, pivot)
}

tensor_btrisolve_ <- function(x, LU_data, LU_pivots) {
    .Call('_torch_tensor_btrisolve_', PACKAGE = 'torch', x, LU_data, LU_pivots)
}

tensor_cauchy__ <- function(x, median, sigma) {
    .Call('_torch_tensor_cauchy__', PACKAGE = 'torch', x, median, sigma)
}

tensor_ceil_ <- function(x) {
    .Call('_torch_tensor_ceil_', PACKAGE = 'torch', x)
}

tensor_ceil__ <- function(x) {
    .Call('_torch_tensor_ceil__', PACKAGE = 'torch', x)
}

tensor_chunk_ <- function(x, chunks, dim) {
    .Call('_torch_tensor_chunk_', PACKAGE = 'torch', x, chunks, dim)
}

tensor_clamp_ <- function(x, min, max) {
    .Call('_torch_tensor_clamp_', PACKAGE = 'torch', x, min, max)
}

tensor_clamp__ <- function(x, min, max) {
    .Call('_torch_tensor_clamp__', PACKAGE = 'torch', x, min, max)
}

tensor_clamp_max_ <- function(x, max) {
    .Call('_torch_tensor_clamp_max_', PACKAGE = 'torch', x, max)
}

tensor_clamp_max__ <- function(x, max) {
    .Call('_torch_tensor_clamp_max__', PACKAGE = 'torch', x, max)
}

tensor_clamp_min_ <- function(x, min) {
    .Call('_torch_tensor_clamp_min_', PACKAGE = 'torch', x, min)
}

tensor_clamp_min__ <- function(x, min) {
    .Call('_torch_tensor_clamp_min__', PACKAGE = 'torch', x, min)
}

tensor_clone_ <- function(x) {
    .Call('_torch_tensor_clone_', PACKAGE = 'torch', x)
}

tensor_contiguous_ <- function(x) {
    .Call('_torch_tensor_contiguous_', PACKAGE = 'torch', x)
}

tensor_copy__ <- function(x, src, non_blocking = FALSE) {
    .Call('_torch_tensor_copy__', PACKAGE = 'torch', x, src, non_blocking)
}

tensor_cos_ <- function(x) {
    .Call('_torch_tensor_cos_', PACKAGE = 'torch', x)
}

tensor_cos__ <- function(x) {
    .Call('_torch_tensor_cos__', PACKAGE = 'torch', x)
}

tensor_cosh_ <- function(x) {
    .Call('_torch_tensor_cosh_', PACKAGE = 'torch', x)
}

tensor_cosh__ <- function(x) {
    .Call('_torch_tensor_cosh__', PACKAGE = 'torch', x)
}

tensor_cpu_ <- function(x) {
    .Call('_torch_tensor_cpu_', PACKAGE = 'torch', x)
}

tensor_cross_ <- function(x, other, dim = -1L) {
    .Call('_torch_tensor_cross_', PACKAGE = 'torch', x, other, dim)
}

tensor_cuda_ <- function(x) {
    .Call('_torch_tensor_cuda_', PACKAGE = 'torch', x)
}

tensor_cumprod_ <- function(x, dim) {
    .Call('_torch_tensor_cumprod_', PACKAGE = 'torch', x, dim)
}

tensor_cumsum_ <- function(x, dim) {
    .Call('_torch_tensor_cumsum_', PACKAGE = 'torch', x, dim)
}

tensor_data_ <- function(x) {
    .Call('_torch_tensor_data_', PACKAGE = 'torch', x)
}

tensor_det_ <- function(x) {
    .Call('_torch_tensor_det_', PACKAGE = 'torch', x)
}

tensor_detach_ <- function(x) {
    .Call('_torch_tensor_detach_', PACKAGE = 'torch', x)
}

tensor_detach__ <- function(x) {
    .Call('_torch_tensor_detach__', PACKAGE = 'torch', x)
}

tensor_device_ <- function(x) {
    .Call('_torch_tensor_device_', PACKAGE = 'torch', x)
}

tensor_diag_ <- function(x, diagonal = 0L) {
    .Call('_torch_tensor_diag_', PACKAGE = 'torch', x, diagonal)
}

tensor_diagflat_ <- function(x, offset = 0L) {
    .Call('_torch_tensor_diagflat_', PACKAGE = 'torch', x, offset)
}

tensor_diagonal_ <- function(x, offset = 0L, dim1 = 0L, dim2 = 1L) {
    .Call('_torch_tensor_diagonal_', PACKAGE = 'torch', x, offset, dim1, dim2)
}

tensor_digamma_ <- function(x) {
    .Call('_torch_tensor_digamma_', PACKAGE = 'torch', x)
}

tensor_digamma__ <- function(x) {
    .Call('_torch_tensor_digamma__', PACKAGE = 'torch', x)
}

tensor_dim_ <- function(x) {
    .Call('_torch_tensor_dim_', PACKAGE = 'torch', x)
}

tensor_dist_ <- function(x, other, p) {
    .Call('_torch_tensor_dist_', PACKAGE = 'torch', x, other, p)
}

tensor_div_tensor_ <- function(x, other) {
    .Call('_torch_tensor_div_tensor_', PACKAGE = 'torch', x, other)
}

tensor_div_scalar_ <- function(x, other) {
    .Call('_torch_tensor_div_scalar_', PACKAGE = 'torch', x, other)
}

tensor_div_tensor__ <- function(x, other) {
    .Call('_torch_tensor_div_tensor__', PACKAGE = 'torch', x, other)
}

tensor_div_scalar__ <- function(x, other) {
    .Call('_torch_tensor_div_scalar__', PACKAGE = 'torch', x, other)
}

tensor_dot_ <- function(x, tensor) {
    .Call('_torch_tensor_dot_', PACKAGE = 'torch', x, tensor)
}

tensor_eig_ <- function(x, eigenvectors = FALSE) {
    .Call('_torch_tensor_eig_', PACKAGE = 'torch', x, eigenvectors)
}

tensor_eq_scalar_ <- function(x, other) {
    .Call('_torch_tensor_eq_scalar_', PACKAGE = 'torch', x, other)
}

tensor_eq_tensor_ <- function(x, other) {
    .Call('_torch_tensor_eq_tensor_', PACKAGE = 'torch', x, other)
}

tensor_gels_ <- function(x, A) {
    .Call('_torch_tensor_gels_', PACKAGE = 'torch', x, A)
}

tensor_grad_ <- function(x) {
    .Call('_torch_tensor_grad_', PACKAGE = 'torch', x)
}

tensor_mean_ <- function(x, dim, keepdim, dtype) {
    .Call('_torch_tensor_mean_', PACKAGE = 'torch', x, dim, keepdim, dtype)
}

tensor_mm_ <- function(x, mat2) {
    .Call('_torch_tensor_mm_', PACKAGE = 'torch', x, mat2)
}

tensor_mul_tensor_ <- function(x, other) {
    .Call('_torch_tensor_mul_tensor_', PACKAGE = 'torch', x, other)
}

tensor_mul_scalar_ <- function(x, other) {
    .Call('_torch_tensor_mul_scalar_', PACKAGE = 'torch', x, other)
}

tensor_permute_ <- function(x, dims) {
    .Call('_torch_tensor_permute_', PACKAGE = 'torch', x, dims)
}

tensor_pow_tensor_ <- function(x, exponent) {
    .Call('_torch_tensor_pow_tensor_', PACKAGE = 'torch', x, exponent)
}

tensor_pow_scalar_ <- function(x, exponent) {
    .Call('_torch_tensor_pow_scalar_', PACKAGE = 'torch', x, exponent)
}

tensor_qr_ <- function(x) {
    .Call('_torch_tensor_qr_', PACKAGE = 'torch', x)
}

tensor_sub_tensor_ <- function(x, other, alpha) {
    .Call('_torch_tensor_sub_tensor_', PACKAGE = 'torch', x, other, alpha)
}

tensor_sub_scalar_ <- function(x, other, alpha) {
    .Call('_torch_tensor_sub_scalar_', PACKAGE = 'torch', x, other, alpha)
}

tensor_sub_tensor__ <- function(x, other, alpha) {
    .Call('_torch_tensor_sub_tensor__', PACKAGE = 'torch', x, other, alpha)
}

tensor_sub_scalar__ <- function(x, other, alpha) {
    .Call('_torch_tensor_sub_scalar__', PACKAGE = 'torch', x, other, alpha)
}

tensor_sum_ <- function(x, dim, keepdim, dtype) {
    .Call('_torch_tensor_sum_', PACKAGE = 'torch', x, dim, keepdim, dtype)
}

tensor_t_ <- function(x) {
    .Call('_torch_tensor_t_', PACKAGE = 'torch', x)
}

tensor_to_ <- function(x, dtype, device, requires_grad) {
    .Call('_torch_tensor_to_', PACKAGE = 'torch', x, dtype, device, requires_grad)
}

tensor_zero__ <- function(x) {
    .Call('_torch_tensor_zero__', PACKAGE = 'torch', x)
}

