# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tensor_ <- function(x, dim, clone = TRUE) {
    .Call('_torch_tensor_', PACKAGE = 'torch', x, dim, clone)
}

tensor_print_ <- function(x) {
    invisible(.Call('_torch_tensor_print_', PACKAGE = 'torch', x))
}

as_array_tensor_ <- function(x) {
    .Call('_torch_as_array_tensor_', PACKAGE = 'torch', x)
}

tensor_abs_ <- function(x) {
    .Call('_torch_tensor_abs_', PACKAGE = 'torch', x)
}

tensor_acos_ <- function(x) {
    .Call('_torch_tensor_acos_', PACKAGE = 'torch', x)
}

tensor_add_ <- function(x, y) {
    .Call('_torch_tensor_add_', PACKAGE = 'torch', x, y)
}

tensor_to_string_ <- function(x) {
    .Call('_torch_tensor_to_string_', PACKAGE = 'torch', x)
}

