# Autogenerated file

# `torch::Tensor`$set("public", "backward", function(gradient = {}, keep_graph = FALSE, create_graph = FALSE) {
#     args <- as.list(environment())
#   args[["self"]] <- self$pointer
#   `torch::Tensor`$dispatch(do.call(torch_backward_, args))
# })

`torch::Tensor`$set("public", "set_data", function(new_data) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_set_data_, args))
})

`torch::Tensor`$set("public", "abs", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_abs_, args))
})

`torch::Tensor`$set("public", "abs_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_abs__, args))
})

`torch::Tensor`$set("public", "acos", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_acos_, args))
})

`torch::Tensor`$set("public", "acos_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_acos__, args))
})

`torch::Tensor`$set("public", "add", function(other, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_add_, args))
})

`torch::Tensor`$set("public", "add_", function(other, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_add__, args))
})

`torch::Tensor`$set("public", "addmv", function(mat, vec, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addmv_, args))
})

`torch::Tensor`$set("public", "addmv_", function(mat, vec, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addmv__, args))
})

`torch::Tensor`$set("public", "addr", function(vec1, vec2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addr_, args))
})

`torch::Tensor`$set("public", "addr_", function(vec1, vec2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addr__, args))
})

`torch::Tensor`$set("public", "all", function(dim, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_all_, args))
})

`torch::Tensor`$set("public", "allclose", function(other, rtol = 1e-05, atol = 1e-08, equal_nan = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_allclose_, args))
})

`torch::Tensor`$set("public", "any", function(dim, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_any_, args))
})

`torch::Tensor`$set("public", "argmax", function(dim = NULL, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_argmax_, args))
})

`torch::Tensor`$set("public", "argmin", function(dim = NULL, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_argmin_, args))
})

`torch::Tensor`$set("public", "as_strided", function(size, stride, storage_offset = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_as_strided_, args))
})

`torch::Tensor`$set("public", "as_strided_", function(size, stride, storage_offset = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_as_strided__, args))
})

`torch::Tensor`$set("public", "asin", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_asin_, args))
})

`torch::Tensor`$set("public", "asin_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_asin__, args))
})

`torch::Tensor`$set("public", "atan", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_atan_, args))
})

`torch::Tensor`$set("public", "atan_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_atan__, args))
})

`torch::Tensor`$set("public", "baddbmm", function(batch1, batch2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_baddbmm_, args))
})

`torch::Tensor`$set("public", "baddbmm_", function(batch1, batch2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_baddbmm__, args))
})

`torch::Tensor`$set("public", "bernoulli", function(p) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_bernoulli_, args))
})

`torch::Tensor`$set("public", "bernoulli_", function(p) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_bernoulli__, args))
})

# `torch::Tensor`$set("public", "bincount", function(weights = {}, minlength = 0) {
#     args <- as.list(environment())
#   args[["self"]] <- self$pointer
#   `torch::Tensor`$dispatch(do.call(torch_bincount_, args))
# })

`torch::Tensor`$set("public", "bitwise_not", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_bitwise_not_, args))
})

`torch::Tensor`$set("public", "bitwise_not_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_bitwise_not__, args))
})

`torch::Tensor`$set("public", "bmm", function(mat2) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_bmm_, args))
})

`torch::Tensor`$set("public", "ceil", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ceil_, args))
})

`torch::Tensor`$set("public", "ceil_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ceil__, args))
})

`torch::Tensor`$set("public", "chunk", function(chunks, dim = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_chunk_, args))
})

`torch::Tensor`$set("public", "clamp", function(min = NULL, max = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_clamp_, args))
})

`torch::Tensor`$set("public", "clamp_", function(min = NULL, max = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_clamp__, args))
})

`torch::Tensor`$set("public", "clamp_max", function(max) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_clamp_max_, args))
})

`torch::Tensor`$set("public", "clamp_max_", function(max) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_clamp_max__, args))
})

`torch::Tensor`$set("public", "clamp_min", function(min) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_clamp_min_, args))
})

`torch::Tensor`$set("public", "clamp_min_", function(min) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_clamp_min__, args))
})

`torch::Tensor`$set("public", "contiguous", function(memory_format = MemoryFormat::Contiguous) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_contiguous_, args))
})

`torch::Tensor`$set("public", "copy_", function(src, non_blocking = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_copy__, args))
})

`torch::Tensor`$set("public", "cos", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cos_, args))
})

`torch::Tensor`$set("public", "cos_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cos__, args))
})

`torch::Tensor`$set("public", "cosh", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cosh_, args))
})

`torch::Tensor`$set("public", "cosh_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cosh__, args))
})

`torch::Tensor`$set("public", "cumsum", function(dim, dtype = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cumsum_, args))
})

`torch::Tensor`$set("public", "cumprod", function(dim, dtype = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cumprod_, args))
})

`torch::Tensor`$set("public", "det", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_det_, args))
})

`torch::Tensor`$set("public", "diag_embed", function(offset = 0, dim1 = -2, dim2 = -1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_diag_embed_, args))
})

`torch::Tensor`$set("public", "diagflat", function(offset = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_diagflat_, args))
})

`torch::Tensor`$set("public", "diagonal", function(offset = 0, dim1 = 0, dim2 = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_diagonal_, args))
})

`torch::Tensor`$set("public", "fill_diagonal_", function(fill_value, wrap = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_fill_diagonal__, args))
})

`torch::Tensor`$set("public", "div", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_div_, args))
})

`torch::Tensor`$set("public", "div_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_div__, args))
})

`torch::Tensor`$set("public", "dot", function(tensor) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_dot_, args))
})

`torch::Tensor`$set("public", "resize_", function(size) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_resize__, args))
})

`torch::Tensor`$set("public", "erf", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_erf_, args))
})

`torch::Tensor`$set("public", "erf_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_erf__, args))
})

`torch::Tensor`$set("public", "erfc", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_erfc_, args))
})

`torch::Tensor`$set("public", "erfc_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_erfc__, args))
})

`torch::Tensor`$set("public", "exp", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_exp_, args))
})

`torch::Tensor`$set("public", "exp_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_exp__, args))
})

`torch::Tensor`$set("public", "expm1", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_expm1_, args))
})

`torch::Tensor`$set("public", "expm1_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_expm1__, args))
})

`torch::Tensor`$set("public", "expand", function(size, implicit = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_expand_, args))
})

`torch::Tensor`$set("public", "expand_as", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_expand_as_, args))
})

`torch::Tensor`$set("public", "flatten", function(start_dim = 0, end_dim = -1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_flatten_, args))
})

`torch::Tensor`$set("public", "fill_", function(value) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_fill__, args))
})

`torch::Tensor`$set("public", "floor", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_floor_, args))
})

`torch::Tensor`$set("public", "floor_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_floor__, args))
})

`torch::Tensor`$set("public", "frac", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_frac_, args))
})

`torch::Tensor`$set("public", "frac_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_frac__, args))
})

`torch::Tensor`$set("public", "ger", function(vec2) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ger_, args))
})

`torch::Tensor`$set("public", "fft", function(signal_ndim, normalized = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_fft_, args))
})

`torch::Tensor`$set("public", "ifft", function(signal_ndim, normalized = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ifft_, args))
})

`torch::Tensor`$set("public", "rfft", function(signal_ndim, normalized = FALSE, onesided = TRUE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_rfft_, args))
})

# `torch::Tensor`$set("public", "irfft", function(signal_ndim, normalized = FALSE, onesided = TRUE, signal_sizes = {}) {
#     args <- as.list(environment())
#   args[["self"]] <- self$pointer
#   `torch::Tensor`$dispatch(do.call(torch_irfft_, args))
# })

`torch::Tensor`$set("public", "index", function(indices) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_, args))
})

`torch::Tensor`$set("public", "index_copy_", function(dim, index, source) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_copy__, args))
})

`torch::Tensor`$set("public", "index_copy", function(dim, index, source) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_copy_, args))
})

`torch::Tensor`$set("public", "index_put_", function(indices, values, accumulate = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_put__, args))
})

`torch::Tensor`$set("public", "index_put", function(indices, values, accumulate = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_put_, args))
})

`torch::Tensor`$set("public", "inverse", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_inverse_, args))
})

`torch::Tensor`$set("public", "isclose", function(other, rtol = 1e-05, atol = 1e-08, equal_nan = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_isclose_, args))
})

`torch::Tensor`$set("public", "is_distributed", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_is_distributed_, args))
})

`torch::Tensor`$set("public", "is_floating_point", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_is_floating_point_, args))
})

`torch::Tensor`$set("public", "is_complex", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_is_complex_, args))
})

`torch::Tensor`$set("public", "is_nonzero", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_is_nonzero_, args))
})

`torch::Tensor`$set("public", "is_same_size", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_is_same_size_, args))
})

`torch::Tensor`$set("public", "is_signed", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_is_signed_, args))
})

`torch::Tensor`$set("public", "kthvalue", function(k, dim = -1, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_kthvalue_, args))
})

`torch::Tensor`$set("public", "log", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log_, args))
})

`torch::Tensor`$set("public", "log_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log__, args))
})

`torch::Tensor`$set("public", "log10", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log10_, args))
})

`torch::Tensor`$set("public", "log10_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log10__, args))
})

`torch::Tensor`$set("public", "log1p", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log1p_, args))
})

`torch::Tensor`$set("public", "log1p_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log1p__, args))
})

`torch::Tensor`$set("public", "log2", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log2_, args))
})

`torch::Tensor`$set("public", "log2_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log2__, args))
})

`torch::Tensor`$set("public", "logdet", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_logdet_, args))
})

`torch::Tensor`$set("public", "log_softmax", function(dim, dtype = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log_softmax_, args))
})

`torch::Tensor`$set("public", "logsumexp", function(dim, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_logsumexp_, args))
})

`torch::Tensor`$set("public", "matmul", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_matmul_, args))
})

`torch::Tensor`$set("public", "matrix_power", function(n) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_matrix_power_, args))
})

`torch::Tensor`$set("public", "max", function(dim, other, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_max_, args))
})

`torch::Tensor`$set("public", "max_values", function(dim, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_max_values_, args))
})

`torch::Tensor`$set("public", "mean", function(dim, keepdim = FALSE, dtype = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_mean_, args))
})

`torch::Tensor`$set("public", "median", function(dim, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_median_, args))
})

`torch::Tensor`$set("public", "min", function(dim, other, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_min_, args))
})

`torch::Tensor`$set("public", "min_values", function(dim, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_min_values_, args))
})

`torch::Tensor`$set("public", "mm", function(mat2) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_mm_, args))
})

`torch::Tensor`$set("public", "mode", function(dim = -1, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_mode_, args))
})

`torch::Tensor`$set("public", "mul", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_mul_, args))
})

`torch::Tensor`$set("public", "mul_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_mul__, args))
})

`torch::Tensor`$set("public", "mv", function(vec) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_mv_, args))
})

`torch::Tensor`$set("public", "mvlgamma", function(p) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_mvlgamma_, args))
})

`torch::Tensor`$set("public", "mvlgamma_", function(p) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_mvlgamma__, args))
})

`torch::Tensor`$set("public", "narrow_copy", function(dim, start, length) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_narrow_copy_, args))
})

`torch::Tensor`$set("public", "narrow", function(dim, start, length) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_narrow_, args))
})

`torch::Tensor`$set("public", "permute", function(dims) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_permute_, args))
})

`torch::Tensor`$set("public", "numpy_T", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_numpy_T_, args))
})

`torch::Tensor`$set("public", "pin_memory", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_pin_memory_, args))
})

`torch::Tensor`$set("public", "pinverse", function(rcond = 1e-15) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_pinverse_, args))
})

`torch::Tensor`$set("public", "reciprocal", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_reciprocal_, args))
})

`torch::Tensor`$set("public", "reciprocal_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_reciprocal__, args))
})

`torch::Tensor`$set("public", "neg", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_neg_, args))
})

`torch::Tensor`$set("public", "neg_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_neg__, args))
})

`torch::Tensor`$set("public", "repeat", function(repeats) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_repeat_, args))
})

`torch::Tensor`$set("public", "repeat_interleave", function(repeats, dim = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_repeat_interleave_, args))
})

`torch::Tensor`$set("public", "reshape", function(shape) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_reshape_, args))
})

`torch::Tensor`$set("public", "reshape_as", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_reshape_as_, args))
})

`torch::Tensor`$set("public", "round", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_round_, args))
})

`torch::Tensor`$set("public", "round_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_round__, args))
})

`torch::Tensor`$set("public", "relu", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_relu_, args))
})

`torch::Tensor`$set("public", "relu_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_relu__, args))
})

`torch::Tensor`$set("public", "prelu", function(weight) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_prelu_, args))
})

`torch::Tensor`$set("public", "prelu_backward", function(grad_output, weight) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_prelu_backward_, args))
})

`torch::Tensor`$set("public", "hardshrink", function(lambd = 0.5) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_hardshrink_, args))
})

`torch::Tensor`$set("public", "hardshrink_backward", function(grad_out, lambd) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_hardshrink_backward_, args))
})

`torch::Tensor`$set("public", "rsqrt", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_rsqrt_, args))
})

`torch::Tensor`$set("public", "rsqrt_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_rsqrt__, args))
})

`torch::Tensor`$set("public", "select", function(dim, index) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_select_, args))
})

`torch::Tensor`$set("public", "sigmoid", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sigmoid_, args))
})

`torch::Tensor`$set("public", "sigmoid_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sigmoid__, args))
})

`torch::Tensor`$set("public", "sin", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sin_, args))
})

`torch::Tensor`$set("public", "sin_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sin__, args))
})

`torch::Tensor`$set("public", "sinh", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sinh_, args))
})

`torch::Tensor`$set("public", "sinh_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sinh__, args))
})

`torch::Tensor`$set("public", "detach", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_detach_, args))
})

`torch::Tensor`$set("public", "detach_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_detach__, args))
})

`torch::Tensor`$set("public", "size", function(dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_size_, args))
})

`torch::Tensor`$set("public", "slice", function(dim = 0, start = 0, end = 9223372036854775807, step = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_slice_, args))
})

`torch::Tensor`$set("public", "slogdet", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_slogdet_, args))
})

`torch::Tensor`$set("public", "smm", function(mat2) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_smm_, args))
})

`torch::Tensor`$set("public", "softmax", function(dim, dtype = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_softmax_, args))
})

`torch::Tensor`$set("public", "split", function(split_size, dim = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_split_, args))
})

`torch::Tensor`$set("public", "split_with_sizes", function(split_sizes, dim = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_split_with_sizes_, args))
})

`torch::Tensor`$set("public", "squeeze", function(dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_squeeze_, args))
})

`torch::Tensor`$set("public", "squeeze_", function(dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_squeeze__, args))
})

`torch::Tensor`$set("public", "sspaddmm", function(mat1, mat2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sspaddmm_, args))
})

# `torch::Tensor`$set("public", "stft", function(n_fft, hop_length = NULL, win_length = NULL, window = {}, normalized = FALSE, onesided = TRUE) {
#     args <- as.list(environment())
#   args[["self"]] <- self$pointer
#   `torch::Tensor`$dispatch(do.call(torch_stft_, args))
# })

`torch::Tensor`$set("public", "stride", function(dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_stride_, args))
})

`torch::Tensor`$set("public", "sum", function(dim, keepdim = FALSE, dtype = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sum_, args))
})

`torch::Tensor`$set("public", "sum_to_size", function(size) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sum_to_size_, args))
})

`torch::Tensor`$set("public", "sqrt", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sqrt_, args))
})

`torch::Tensor`$set("public", "sqrt_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sqrt__, args))
})

`torch::Tensor`$set("public", "std", function(dim, unbiased = TRUE, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_std_, args))
})

`torch::Tensor`$set("public", "prod", function(dim, keepdim = FALSE, dtype = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_prod_, args))
})

`torch::Tensor`$set("public", "t", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_t_, args))
})

`torch::Tensor`$set("public", "t_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_t__, args))
})

`torch::Tensor`$set("public", "tan", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_tan_, args))
})

`torch::Tensor`$set("public", "tan_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_tan__, args))
})

`torch::Tensor`$set("public", "tanh", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_tanh_, args))
})

`torch::Tensor`$set("public", "tanh_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_tanh__, args))
})

`torch::Tensor`$set("public", "transpose", function(dim0, dim1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_transpose_, args))
})

`torch::Tensor`$set("public", "transpose_", function(dim0, dim1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_transpose__, args))
})

`torch::Tensor`$set("public", "flip", function(dims) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_flip_, args))
})

# `torch::Tensor`$set("public", "roll", function(shifts, dims = {}) {
#     args <- as.list(environment())
#   args[["self"]] <- self$pointer
#   `torch::Tensor`$dispatch(do.call(torch_roll_, args))
# })

# `torch::Tensor`$set("public", "rot90", function(k = 1, dims = {0,1}) {
#     args <- as.list(environment())
#   args[["self"]] <- self$pointer
#   `torch::Tensor`$dispatch(do.call(torch_rot90_, args))
# })

`torch::Tensor`$set("public", "trunc", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_trunc_, args))
})

`torch::Tensor`$set("public", "trunc_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_trunc__, args))
})

`torch::Tensor`$set("public", "type_as", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_type_as_, args))
})

`torch::Tensor`$set("public", "unsqueeze", function(dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_unsqueeze_, args))
})

`torch::Tensor`$set("public", "unsqueeze_", function(dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_unsqueeze__, args))
})

`torch::Tensor`$set("public", "var", function(dim, unbiased = TRUE, keepdim = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_var_, args))
})

`torch::Tensor`$set("public", "view_as", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_view_as_, args))
})

`torch::Tensor`$set("public", "where", function(condition, other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_where_, args))
})

`torch::Tensor`$set("public", "norm", function(p, dim, keepdim, dtype) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_norm_, args))
})

`torch::Tensor`$set("public", "clone", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_clone_, args))
})

`torch::Tensor`$set("public", "resize_as_", function(the_template) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_resize_as__, args))
})

`torch::Tensor`$set("public", "pow", function(exponent) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_pow_, args))
})

`torch::Tensor`$set("public", "zero_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_zero__, args))
})

`torch::Tensor`$set("public", "sub", function(other, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sub_, args))
})

`torch::Tensor`$set("public", "sub_", function(other, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sub__, args))
})

`torch::Tensor`$set("public", "addmm", function(mat1, mat2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addmm_, args))
})

`torch::Tensor`$set("public", "addmm_", function(mat1, mat2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addmm__, args))
})

`torch::Tensor`$set("public", "sparse_resize_", function(size, sparse_dim, dense_dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sparse_resize__, args))
})

`torch::Tensor`$set("public", "sparse_resize_and_clear_", function(size, sparse_dim, dense_dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sparse_resize_and_clear__, args))
})

`torch::Tensor`$set("public", "sparse_mask", function(mask) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sparse_mask_, args))
})

`torch::Tensor`$set("public", "to_dense", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_to_dense_, args))
})

`torch::Tensor`$set("public", "sparse_dim", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sparse_dim_, args))
})

`torch::Tensor`$set("public", "_dimI", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch__dimI_, args))
})

`torch::Tensor`$set("public", "dense_dim", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_dense_dim_, args))
})

`torch::Tensor`$set("public", "_dimV", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch__dimV_, args))
})

`torch::Tensor`$set("public", "_nnz", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch__nnz_, args))
})

`torch::Tensor`$set("public", "coalesce", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_coalesce_, args))
})

`torch::Tensor`$set("public", "is_coalesced", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_is_coalesced_, args))
})

`torch::Tensor`$set("public", "_indices", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch__indices_, args))
})

`torch::Tensor`$set("public", "_values", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch__values_, args))
})

`torch::Tensor`$set("public", "_coalesced_", function(coalesced) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch__coalesced__, args))
})

`torch::Tensor`$set("public", "indices", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_indices_, args))
})

`torch::Tensor`$set("public", "values", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_values_, args))
})

`torch::Tensor`$set("public", "numel", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_numel_, args))
})

`torch::Tensor`$set("public", "unbind", function(dim = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_unbind_, args))
})

`torch::Tensor`$set("public", "to_sparse", function(sparse_dim) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_to_sparse_, args))
})

`torch::Tensor`$set("public", "to_mkldnn", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_to_mkldnn_, args))
})

`torch::Tensor`$set("public", "dequantize", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_dequantize_, args))
})

`torch::Tensor`$set("public", "q_scale", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_q_scale_, args))
})

`torch::Tensor`$set("public", "q_zero_point", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_q_zero_point_, args))
})

`torch::Tensor`$set("public", "int_repr", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_int_repr_, args))
})

`torch::Tensor`$set("public", "qscheme", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_qscheme_, args))
})

`torch::Tensor`$set("public", "to", function(options, device, other, dtype, non_blocking = FALSE, copy = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_to_, args))
})

`torch::Tensor`$set("public", "item", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_item_, args))
})

# `torch::Tensor`$set("public", "set_", function(source, storage_offset, size, stride = {}) {
#     args <- as.list(environment())
#   args[["self"]] <- self$pointer
#   `torch::Tensor`$dispatch(do.call(torch_set__, args))
# })

`torch::Tensor`$set("public", "set_quantizer_", function(quantizer) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_set_quantizer__, args))
})

`torch::Tensor`$set("public", "is_set_to", function(tensor) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_is_set_to_, args))
})

`torch::Tensor`$set("public", "masked_fill_", function(mask, value) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_masked_fill__, args))
})

`torch::Tensor`$set("public", "masked_fill", function(mask, value) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_masked_fill_, args))
})

`torch::Tensor`$set("public", "masked_scatter_", function(mask, source) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_masked_scatter__, args))
})

`torch::Tensor`$set("public", "masked_scatter", function(mask, source) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_masked_scatter_, args))
})

`torch::Tensor`$set("public", "view", function(size) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_view_, args))
})

`torch::Tensor`$set("public", "put_", function(index, source, accumulate = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_put__, args))
})

`torch::Tensor`$set("public", "index_add_", function(dim, index, source) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_add__, args))
})

`torch::Tensor`$set("public", "index_add", function(dim, index, source) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_add_, args))
})

`torch::Tensor`$set("public", "index_fill_", function(dim, index, value) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_fill__, args))
})

`torch::Tensor`$set("public", "index_fill", function(dim, index, value) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_fill_, args))
})

`torch::Tensor`$set("public", "scatter_", function(dim, index, src, value) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_scatter__, args))
})

`torch::Tensor`$set("public", "scatter", function(dim, index, src, value) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_scatter_, args))
})

`torch::Tensor`$set("public", "scatter_add_", function(dim, index, src) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_scatter_add__, args))
})

`torch::Tensor`$set("public", "scatter_add", function(dim, index, src) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_scatter_add_, args))
})

`torch::Tensor`$set("public", "lt_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_lt__, args))
})

`torch::Tensor`$set("public", "gt_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_gt__, args))
})

`torch::Tensor`$set("public", "le_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_le__, args))
})

`torch::Tensor`$set("public", "ge_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ge__, args))
})

`torch::Tensor`$set("public", "eq_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_eq__, args))
})

`torch::Tensor`$set("public", "ne_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ne__, args))
})

`torch::Tensor`$set("public", "__and__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___and___, args))
})

`torch::Tensor`$set("public", "__iand__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___iand___, args))
})

`torch::Tensor`$set("public", "__or__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___or___, args))
})

`torch::Tensor`$set("public", "__ior__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___ior___, args))
})

`torch::Tensor`$set("public", "__xor__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___xor___, args))
})

`torch::Tensor`$set("public", "__ixor__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___ixor___, args))
})

`torch::Tensor`$set("public", "__lshift__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___lshift___, args))
})

`torch::Tensor`$set("public", "__ilshift__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___ilshift___, args))
})

`torch::Tensor`$set("public", "__rshift__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___rshift___, args))
})

`torch::Tensor`$set("public", "__irshift__", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch___irshift___, args))
})

`torch::Tensor`$set("public", "lgamma_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_lgamma__, args))
})

`torch::Tensor`$set("public", "atan2_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_atan2__, args))
})

`torch::Tensor`$set("public", "tril_", function(diagonal = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_tril__, args))
})

`torch::Tensor`$set("public", "triu_", function(diagonal = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_triu__, args))
})

`torch::Tensor`$set("public", "digamma_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_digamma__, args))
})

`torch::Tensor`$set("public", "polygamma_", function(n) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_polygamma__, args))
})

`torch::Tensor`$set("public", "erfinv_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_erfinv__, args))
})

`torch::Tensor`$set("public", "renorm_", function(p, dim, maxnorm) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_renorm__, args))
})

`torch::Tensor`$set("public", "pow_", function(exponent) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_pow__, args))
})

`torch::Tensor`$set("public", "lerp_", function(end, weight) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_lerp__, args))
})

`torch::Tensor`$set("public", "sign_", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sign__, args))
})

`torch::Tensor`$set("public", "fmod_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_fmod__, args))
})

`torch::Tensor`$set("public", "remainder_", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_remainder__, args))
})

`torch::Tensor`$set("public", "addbmm_", function(batch1, batch2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addbmm__, args))
})

`torch::Tensor`$set("public", "addbmm", function(batch1, batch2, beta = 1, alpha = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addbmm_, args))
})

`torch::Tensor`$set("public", "addcmul_", function(tensor1, tensor2, value = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addcmul__, args))
})

`torch::Tensor`$set("public", "addcdiv_", function(tensor1, tensor2, value = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addcdiv__, args))
})

`torch::Tensor`$set("public", "random_", function(from, to) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_random__, args))
})

`torch::Tensor`$set("public", "uniform_", function(from = 0, to = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_uniform__, args))
})

`torch::Tensor`$set("public", "normal_", function(mean = 0, std = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_normal__, args))
})

`torch::Tensor`$set("public", "cauchy_", function(median = 0, sigma = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cauchy__, args))
})

`torch::Tensor`$set("public", "log_normal_", function(mean = 1, std = 2) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_log_normal__, args))
})

`torch::Tensor`$set("public", "exponential_", function(lambd = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_exponential__, args))
})

`torch::Tensor`$set("public", "geometric_", function(p) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_geometric__, args))
})

`torch::Tensor`$set("public", "diag", function(diagonal = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_diag_, args))
})

`torch::Tensor`$set("public", "cross", function(other, dim = NULL) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cross_, args))
})

`torch::Tensor`$set("public", "triu", function(diagonal = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_triu_, args))
})

`torch::Tensor`$set("public", "tril", function(diagonal = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_tril_, args))
})

`torch::Tensor`$set("public", "trace", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_trace_, args))
})

`torch::Tensor`$set("public", "ne", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ne_, args))
})

`torch::Tensor`$set("public", "eq", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_eq_, args))
})

`torch::Tensor`$set("public", "ge", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ge_, args))
})

`torch::Tensor`$set("public", "le", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_le_, args))
})

`torch::Tensor`$set("public", "gt", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_gt_, args))
})

`torch::Tensor`$set("public", "lt", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_lt_, args))
})

`torch::Tensor`$set("public", "take", function(index) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_take_, args))
})

`torch::Tensor`$set("public", "index_select", function(dim, index) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_index_select_, args))
})

`torch::Tensor`$set("public", "masked_select", function(mask) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_masked_select_, args))
})

`torch::Tensor`$set("public", "nonzero", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_nonzero_, args))
})

`torch::Tensor`$set("public", "nonzero_numpy", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_nonzero_numpy_, args))
})

`torch::Tensor`$set("public", "gather", function(dim, index, sparse_grad = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_gather_, args))
})

`torch::Tensor`$set("public", "addcmul", function(tensor1, tensor2, value = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addcmul_, args))
})

`torch::Tensor`$set("public", "addcdiv", function(tensor1, tensor2, value = 1) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_addcdiv_, args))
})

`torch::Tensor`$set("public", "lstsq", function(A) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_lstsq_, args))
})

`torch::Tensor`$set("public", "triangular_solve", function(A, upper = TRUE, transpose = FALSE, unitriangular = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_triangular_solve_, args))
})

`torch::Tensor`$set("public", "symeig", function(eigenvectors = FALSE, upper = TRUE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_symeig_, args))
})

`torch::Tensor`$set("public", "eig", function(eigenvectors = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_eig_, args))
})

`torch::Tensor`$set("public", "svd", function(some = TRUE, compute_uv = TRUE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_svd_, args))
})

`torch::Tensor`$set("public", "cholesky", function(upper = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cholesky_, args))
})

`torch::Tensor`$set("public", "cholesky_solve", function(input2, upper = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cholesky_solve_, args))
})

`torch::Tensor`$set("public", "solve", function(A) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_solve_, args))
})

`torch::Tensor`$set("public", "cholesky_inverse", function(upper = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_cholesky_inverse_, args))
})

`torch::Tensor`$set("public", "qr", function(some = TRUE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_qr_, args))
})

`torch::Tensor`$set("public", "geqrf", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_geqrf_, args))
})

`torch::Tensor`$set("public", "orgqr", function(input2) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_orgqr_, args))
})

`torch::Tensor`$set("public", "ormqr", function(input2, input3, left = TRUE, transpose = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_ormqr_, args))
})

`torch::Tensor`$set("public", "lu_solve", function(LU_data, LU_pivots) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_lu_solve_, args))
})

`torch::Tensor`$set("public", "multinomial", function(num_samples, replacement = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_multinomial_, args))
})

`torch::Tensor`$set("public", "lgamma", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_lgamma_, args))
})

`torch::Tensor`$set("public", "digamma", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_digamma_, args))
})

`torch::Tensor`$set("public", "polygamma", function(n) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_polygamma_, args))
})

`torch::Tensor`$set("public", "erfinv", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_erfinv_, args))
})

`torch::Tensor`$set("public", "dist", function(other, p = 2) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_dist_, args))
})

`torch::Tensor`$set("public", "atan2", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_atan2_, args))
})

`torch::Tensor`$set("public", "lerp", function(end, weight) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_lerp_, args))
})

`torch::Tensor`$set("public", "histc", function(bins = 100, min = 0, max = 0) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_histc_, args))
})

`torch::Tensor`$set("public", "sign", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sign_, args))
})

`torch::Tensor`$set("public", "fmod", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_fmod_, args))
})

`torch::Tensor`$set("public", "remainder", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_remainder_, args))
})

`torch::Tensor`$set("public", "sort", function(dim = -1, descending = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_sort_, args))
})

`torch::Tensor`$set("public", "argsort", function(dim = -1, descending = FALSE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_argsort_, args))
})

`torch::Tensor`$set("public", "topk", function(k, dim = -1, largest = TRUE, sorted = TRUE) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_topk_, args))
})

`torch::Tensor`$set("public", "renorm", function(p, dim, maxnorm) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_renorm_, args))
})

`torch::Tensor`$set("public", "unfold", function(dimension, size, step) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_unfold_, args))
})

`torch::Tensor`$set("public", "equal", function(other) {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_equal_, args))
})

`torch::Tensor`$set("public", "alias", function() {
    args <- as.list(environment())
  args[["self"]] <- self$pointer
  `torch::Tensor`$dispatch(do.call(torch_alias_, args))
})
